---
- name: Install apache
  hosts: all
  become: yes
  tasks:
    - name: Install apache
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: present
    - name: Clone the GitHub repository
      ansible.builtin.git:
        repo: 'https://github.com/beingKhanvilkar/ansible_project.git' # Replace with your repository URL
        dest: '/tmp/my_repo_clone' # Temporary directory for cloning
        version: main # Or the specific branch/tag you want
        force: yes # Overwrite if directory exists
    - name: remove file
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent
    - name: Copy file
      ansible.builtin.file:
        src: '/tmp/my_repo_clone/index.html'
        dest: '/var/www/html/'
        
